version: "3.9"

services:
  lumen:
    ports:
      - "8080:8080"
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    build: .
    command: php -S lumen:8080 -t public
    restart: always
    depends_on:
      - lumenDemodb
  lumenDemodb:
    image: mysql:8.0
    # command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
